### PR TITLE
Horizontal summary functions

### PR DESCRIPTION
**Pull request by rjbgoudie**
Adds horizontal versions of mean_cl_boot, mean_dl_normal, mean_sdl and
median_hilow (all from Hmisc) and mean_se

Currently they are called *_h, but could easily drop the _ if you think that is more consistent.

### CODE REVIEW

**Comment by mjskay** [comment]
Why not wrap the summary functions themselves, rather than the underlying Hmisc functions? That would reduce code duplication and make it easier to wrap other summary functions (e.g. summary functions in other packages). Something like this:

```{r}
y2x = function(f) function(...)
    plyr::rename(f(...), c(y = "x", ymax = "xmax", ymin = "xmin"), warn_missing=FALSE)
```

Then the summary function definitions would be something like this:

```{r}
mean_cl_booth <- y2x(mean_cl_boot)
mean_cl_normalh <- y2x(mean_cl_normal)
mean_sdlh <- y2x(mean_sdl_h)
median_hilowh <- y2x(median_hilow)
mean_seh <- y2x(mean_se)
```

(whether or not they come from Hmisc).

And custom summary functions could be converted by end-users by changing calls like this:

```{r}
stat_summary(fun.data = some_function)
```

To this:

```{r}
stat_summaryh(fun.data = y2x(some_function))
```

(P.S. came across this pull request right as I was thinking of submitting an issue on this --- consider this another vote for a solution to this problem!) :)

**Comment by rjbgoudie** [comment]
Yes, that is a nice, clean implementation that is more powerful than my approach. For this approach, your y2x() should probably reuse flip_lookup in https://github.com/lionel-/ggstance/blob/7007b0962e38ee9443dcc028c35671224ca02e78/R/flip-aes.R . However, 73f521384ae8ea277db5f7d5a2854004aa18f947 implied to me that @lionel- was now preferring simple code copying to having complex dependencies on ggplot.

**Comment by mjskay** [comment]
You're right! `flip_aes` is a much better way to do this. Using it simplifies the transformation even further:

```{r}
y2x <- function(f) function(...) flip_aes(f(...))
```

Although it occurs to me that the above version of `y2x` is now more generic than just swapping y and x, and could be considered the analog to `flip_aes` applied to a function. So maybe even extending the already-generic `flip_aes` like this:

```{r}
flip_aes.function <- function(x) function(...) flip_aes(x(...))
```

Yielding this usage:

```{r}
stat_summaryh(fun.data = flip_aes(some_function))
```

I noticed that `flip_aes` is currently used internally by ggstance and not exported. I suspect users of ggstance (and I'm including myself here) would find that function useful if exported (whether or not it is extended to support flipping functions).

Your (and @lionel-'s) point about not having complex dependencies on ggplot is well made. I interpret @lionel-'s position as being against dependencies on ggplot internals, which are likely less stable, compared to dependencies on the external interfaces, which are likely more stable. 

In this case I don't think the dependency is complex. I see transforming the results of the summary functions as a dependency on a stable external interface (functions which return data frames of aesthetics): since other packages can also provide summary functions, and the output of summary functions is very simple, I can't see there being much motivation for ggplot to change how they work. The summary functions are also exported by the package, providing at least some reasonable "contract" for their stability, and the transformation of them depends only on their results (not how they are implemented).

**Comment by lionel-** [comment]
Thanks for this!

**Pull request merged**
